# Generated by Django 3.2.5 on 2021-07-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFinal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='listaProductos',
        ),
        migrations.AddField(
            model_name='carrito',
            name='listaProductos',
            field=models.ManyToManyField(blank=True, related_name='Carritos', to='appFinal.Productos'),
        ),
    ]
